version: '3'

services:
  api:
    # Build dockerfile
    build: .
    ports:
      - "3333:3333"
    # Restart container in case of crashes etc
    restart: always
    # Set API to use host networking
    network_mode: host
    # API depends on DB to be there
    depends_on:
      - db
    # Set env variables
    environment:
      APP_KEY: A1jrJ0w_Rv7o-J6BUCVE8RdkWb31HVdt
      PG_PASSWORD: root
      PG_USER: postgres

  db:
    # Set DB version to run
    image: postgres:13.3-alpine
    # Restart container in case of crashes etc
    restart: always
    # Set DB to use host networking
    network_mode: host
    # Set DB env variables
    environment:
      POSTGRES_PASSWORD: root
    # Mount DB data to volume,
    # so we don't lose all DB data over deployments
    volumes:
      - database:/var/lib/postgresql/data

# Define the DB volume
volumes:
  database:
